# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cddc772da90a1dd5406c677d3670045c2b1a127e7066a092ba68a84200999be1de30f9882a33f5702b45afae43dd7804542f0fb24dc73638133f741f7ef62f5e

test:
  secret_key_base: c2ba7d265ba6951d3e3cebc8f97eae389010df6548e1d78023d566ed038aec21c1a5875051aa3453267724f48ff48de6036eea4cf007436e6e3f3dee47b1a90c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
